[theme]
base = "light"
primaryColor = "#0067B9"
backgroundColor = "#F7F9FA"
secondaryBackgroundColor = "#EAF2F7"
textColor = "#173042"
borderColor = "#D7E2E8"
baseRadius = "0.35rem"
font = "sans-serif"
headingFont = "serif"
codeFont = "sans-serif"

[theme.sidebar]
backgroundColor = "#062E46"
textColor = "#F4F8FA"
secondaryBackgroundColor = "#0D3E5B"
borderColor = "#28546C"

[client]
toolbarMode = "viewer"
